development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  postgresql:
    username: <%= ENV['POSTGRESQL_USERNAME'] %>
    password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  pepper_secret_key: <%= ENV['PEPPER_SECRET_KEY'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  postgresql:
    username: <%= ENV['POSTGRESQL_USERNAME'] %>
    password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  pepper_secret_key: <%= ENV['PEPPER_SECRET_KEY'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  postgresql:
    username: <%= ENV['POSTGRESQL_USERNAME'] %>
    password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  pepper_secret_key: <%= ENV['PEPPER_SECRET_KEY'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
